import { Product } from "src/shared/types";

export const products: Product[] = [
  {
    id: 1,
    title: "лего",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 11,
    category: "constructor",
    price: 600,
    isOrdered: false,
  },
  {
    id: 2,
    title: "конструктор",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 10,
    category: "constructor",
    price: 100,
    isOrdered: false,
  },
  {
    id: 3,
    title: "лего дупло",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 0,
    category: "constructor",
    price: 200,
    isOrdered: false,
  },
  {
    id: 4,
    title: "игрушка мягка",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 2,
    category: "girls",
    price: 2300,
    isOrdered: false,
  },
  {
    id: 5,
    title: "игрушка плюшевая",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 6,
    category: "girls",
    price: 1200,
    isOrdered: false,
  },
  {
    id: 6,
    title: "машинка-грузовик",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 0,
    category: "boys",
    price: 1000,
    isOrdered: false,
  },
  {
    id: 7,
    title: "паровоз",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 8,
    category: "boys",
    price: 600,
    isOrdered: false,
  },
  {
    id: 8,
    title: "кукла",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 0,
    category: "girls",
    price: 700,
    isOrdered: false,
  },
  {
    id: 9,
    title: "машинка",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 10,
    category: "boys",
    price: 900,
    isOrdered: false,
  },

  {
    id: 10,
    title: "шашки",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    cart: false,
    count: 8,
    category: "boys",
    price: 800,
    isOrdered: false,
  },
];
