version: "3.8"

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped
    # healthcheck:
    #   test: ["executable", "arg"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
    # TODO: настроить
    volumes:
      - tasks-data:/var/lib/postgresql/data
volumes:
  tasks-data:
