import { Task } from "src/shared/types";

export const data: Task[] = [
  {
    id: "1",
    title: "задача",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: true,
    createdAt: new Date(2023, 5, 23),
    updatedAt: new Date(2023, 5, 23),
  },
  {
    id: "2",
    title: "задача",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: true,
    createdAt: new Date(2021, 5, 23),
    updatedAt: new Date(2021, 5, 23),
  },
  {
    id: "3",
    title: "ура",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(2024, 5, 23),
    updatedAt: new Date(2024, 5, 23),
  },
  {
    id: "4",
    title: "осень",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: true,
    createdAt: new Date(2019, 5, 23),
    updatedAt: new Date(2019, 5, 23),
  },
  {
    id: "5",
    title:
      "лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето лето",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(2006, 5, 23),
    updatedAt: new Date(2006, 5, 23),
  },
  {
    id: "6",
    title: "зима",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(2010, 5, 23),
    updatedAt: new Date(2010, 5, 23),
  },
  {
    id: "7",
    title: "март",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(2019, 5, 23),
    updatedAt: new Date(2019, 5, 23),
  },
  {
    id: "8",
    title: "апрель",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(2015, 5, 23),
    updatedAt: new Date(2015, 5, 23),
  },
  {
    id: "9",
    title: "май",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(2016, 5, 23),
    updatedAt: new Date(2016, 5, 23),
  },
  {
    id: "10",
    title: "июнь",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(2015, 5, 23),
    updatedAt: new Date(2015, 5, 23),
  },
];
