export const data = [
  {
    id: 1,
    title: "Задача 1",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: true,
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: true,
    createdAt: new Date(),
  },
  {
    id: 3,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },
  {
    id: 4,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },
  {
    id: 5,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },
  {
    id: 6,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },
  {
    id: 7,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },
  {
    id: 8,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },
  {
    id: 9,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },

  {
    id: 10,
    title: "Задача 2",
    descr: `Lorem ipsum dolor sit amet consectetur adipisicing elit.`,
    isCompleted: false,
    createdAt: new Date(),
  },
];
